const phoneIcon = document.querySelector('.phone-icon')
const favoriteIcon = document.querySelector('.heart-icon')
const messageIcon = document.querySelector('.message-icon')
const houseContainer = document.querySelector('.house-card-container')
const leftAngle = document.querySelector('.left-angle')
const rightAngle = document.querySelector('.right-angle')
const saleBtn = document.querySelector('.sale-btn')
const rentBtn = document.querySelector('.rent-btn')